In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Collecting numpy<2.0,>=1.18.5 (from gensim)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.1 MB/s eta 0:00:00
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.3.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=1.8.1->gensim) (1.17.3)
Downloading gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 MB 68.7 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 95.3 MB/s eta 0:00:00
Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 15.9 MB/s eta 0:00:00
Installing collected packages: numpy, scipy, gensim
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.1
    Uninstalling scipy-1.16.1:
      Successfully uninstalled scipy-1.16.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tsfresh 0.21.1 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed gensim-4.3.3 numpy-1.26.4 scipy-1.13.1

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.metrics.pairwise import cosine_similarity

import re
import string
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
data = "https://github.com/melody-10/Proyecto_Hoteles_California/blob/main/df_clean_reviews.csv?raw=true"
df = pd.read_csv(data, engine='python')
df.head()

,name,county,ratings,text,clean_review
0,Four Seasons Hotel Los Angeles at Beverly Hills,Los_Angeles,"{'service': 5.0, 'cleanliness': 5.0, 'overall'...",The Four Season LA is probably one of the warm...,four season la probably one warmest friendlies...
1,Four Seasons Hotel Los Angeles at Beverly Hills,Los_Angeles,"{'service': 2.0, 'cleanliness': 4.0, 'overall'...",When you stay in a Four Seasons Hotel you have...,four seasons high expectations remarkable stay...
2,Four Seasons Hotel Los Angeles at Beverly Hills,Los_Angeles,"{'service': 5.0, 'cleanliness': 5.0, 'overall'...",I spent my birthday this year at the Four Seas...,spent birthday four seasons hotel moment picke...
3,Four Seasons Hotel Los Angeles at Beverly Hills,Los_Angeles,"{'service': 5.0, 'cleanliness': 4.0, 'overall'...",I just love this hotel. I stay here for work a...,love hotel work get treated well whenever matt...
4,Four Seasons Hotel Los Angeles at Beverly Hills,Los_Angeles,"{'service': 5.0, 'cleanliness': 5.0, 'overall'...",We had the best hotel experience to date at Th...,best experience date four seasons beverly hill...

In [ ]:
import gensim
from gensim import corpora

clean_corpus = df["clean_review"].apply(lambda x: x.split())

# Creating document-term matrix
dictionary = corpora.Dictionary(clean_corpus)
doc_term_matrix = [dictionary.doc2bow(doc) for doc in clean_corpus]

In [ ]:
from gensim.models import LdaModel

# LDA model
lda = LdaModel(doc_term_matrix, num_topics=9, id2word = dictionary)

# Results
print(lda.print_topics(num_topics=9, num_words=10))

[(0, '0.020*"square" + 0.011*"union" + 0.010*"hotels" + 0.010*"chancellor" + 0.010*"service" + 0.009*"san" + 0.008*"internet" + 0.008*"business" + 0.007*"one" + 0.007*"free"'), (1, '0.020*"rooms" + 0.016*"bathroom" + 0.014*"old" + 0.012*"lobby" + 0.012*"like" + 0.010*"small" + 0.009*"modern" + 0.009*"decor" + 0.007*"new" + 0.006*"bar"'), (2, '0.021*"staff" + 0.020*"great" + 0.013*"san" + 0.011*"service" + 0.011*"us" + 0.011*"francisco" + 0.008*"location" + 0.008*"friendly" + 0.008*"wonderful" + 0.008*"time"'), (3, '0.012*"small" + 0.011*"square" + 0.010*"parking" + 0.010*"nice" + 0.010*"breakfast" + 0.009*"good" + 0.008*"free" + 0.008*"area" + 0.007*"one" + 0.007*"bathroom"'), (4, '0.025*"great" + 0.021*"location" + 0.015*"staff" + 0.012*"car" + 0.012*"good" + 0.012*"clean" + 0.011*"walk" + 0.011*"wharf" + 0.010*"rooms" + 0.010*"nice"'), (5, '0.014*"night" + 0.013*"noise" + 0.011*"would" + 0.009*"could" + 0.009*"floor" + 0.008*"get" + 0.008*"one" + 0.008*"people" + 0.008*"like" + 0.008*"rooms"'), (6, '0.018*"us" + 0.014*"desk" + 0.012*"front" + 0.012*"would" + 0.009*"one" + 0.008*"told" + 0.008*"room" + 0.008*"asked" + 0.007*"day" + 0.007*"get"'), (7, '0.021*"coffee" + 0.016*"nice" + 0.015*"bed" + 0.014*"breakfast" + 0.013*"comfortable" + 0.012*"water" + 0.012*"good" + 0.012*"morning" + 0.010*"bathroom" + 0.009*"wine"'), (8, '0.037*"dog" + 0.036*"rubber" + 0.032*"pet" + 0.021*"dogs" + 0.013*"pets" + 0.011*"n" + 0.010*"bugs" + 0.010*"travelocity" + 0.008*"frank" + 0.008*"medical"')]

In [ ]:
def print_topics(model, num_words=10):
    """
    Prints the topics and their top words from an LDA model.

    Args:
        model: The trained LDA model.
        num_words: The number of top words to print for each topic.
    """
    print("Top topics:")
    for topic_id, topic_words in model.print_topics(num_topics=-1, num_words=num_words):
        print(f"Tópico {topic_id}: {topic_words}")

print_topics(lda)

Top topics:
Tópico 0: 0.020*"square" + 0.011*"union" + 0.010*"hotels" + 0.010*"chancellor" + 0.010*"service" + 0.009*"san" + 0.008*"internet" + 0.008*"business" + 0.007*"one" + 0.007*"free"
Tópico 1: 0.020*"rooms" + 0.016*"bathroom" + 0.014*"old" + 0.012*"lobby" + 0.012*"like" + 0.010*"small" + 0.009*"modern" + 0.009*"decor" + 0.007*"new" + 0.006*"bar"
Tópico 2: 0.021*"staff" + 0.020*"great" + 0.013*"san" + 0.011*"service" + 0.011*"us" + 0.011*"francisco" + 0.008*"location" + 0.008*"friendly" + 0.008*"wonderful" + 0.008*"time"
Tópico 3: 0.012*"small" + 0.011*"square" + 0.010*"parking" + 0.010*"nice" + 0.010*"breakfast" + 0.009*"good" + 0.008*"free" + 0.008*"area" + 0.007*"one" + 0.007*"bathroom"
Tópico 4: 0.025*"great" + 0.021*"location" + 0.015*"staff" + 0.012*"car" + 0.012*"good" + 0.012*"clean" + 0.011*"walk" + 0.011*"wharf" + 0.010*"rooms" + 0.010*"nice"
Tópico 5: 0.014*"night" + 0.013*"noise" + 0.011*"would" + 0.009*"could" + 0.009*"floor" + 0.008*"get" + 0.008*"one" + 0.008*"people" + 0.008*"like" + 0.008*"rooms"
Tópico 6: 0.018*"us" + 0.014*"desk" + 0.012*"front" + 0.012*"would" + 0.009*"one" + 0.008*"told" + 0.008*"room" + 0.008*"asked" + 0.007*"day" + 0.007*"get"
Tópico 7: 0.021*"coffee" + 0.016*"nice" + 0.015*"bed" + 0.014*"breakfast" + 0.013*"comfortable" + 0.012*"water" + 0.012*"good" + 0.012*"morning" + 0.010*"bathroom" + 0.009*"wine"
Tópico 8: 0.037*"dog" + 0.036*"rubber" + 0.032*"pet" + 0.021*"dogs" + 0.013*"pets" + 0.011*"n" + 0.010*"bugs" + 0.010*"travelocity" + 0.008*"frank" + 0.008*"medical"

In [ ]:
# Get topic distributions for each document
topic_distributions = [lda.get_document_topics(doc) for doc in doc_term_matrix]

# Function to get the dominant topic for a document
def get_dominant_topic(topic_list):
    if not topic_list:
        return None
    # Find the topic with the highest probability
    return max(topic_list, key=lambda item: item[1])[0]

# Assign the dominant topic to each review
df["topic"] = [get_dominant_topic(topics) for topics in topic_distributions]

# Define topic labels
topic_labels = {
    0: "Services near Union Square",
    1: "Ammenities and spaces",
    2: "Great time and location",
    3: "Services",
    4: "Location and cleanliness",
    5: "Night life",
    6: "Staff",
    7: "Food and room service",
    8: "Pets"
}

# Map topic numbers to labels
df["topic_label"] = df["topic"].map(topic_labels)

,clean_review,topic,topic_label
0,four season la probably one warmest friendlies...,2,Great time and location
1,four seasons high expectations remarkable stay...,6,Staff
2,spent birthday four seasons hotel moment picke...,2,Great time and location
3,love hotel work get treated well whenever matt...,2,Great time and location
4,best experience date four seasons beverly hill...,2,Great time and location

In [ ]:
# Display the first few rows with the new columns
display(df[["name", "ratings", "text", "topic", "topic_label"]].head())

,name,ratings,text,topic,topic_label
0,Four Seasons Hotel Los Angeles at Beverly Hills,"{'service': 5.0, 'cleanliness': 5.0, 'overall'...",The Four Season LA is probably one of the warm...,2,Great time and location
1,Four Seasons Hotel Los Angeles at Beverly Hills,"{'service': 2.0, 'cleanliness': 4.0, 'overall'...",When you stay in a Four Seasons Hotel you have...,6,Staff
2,Four Seasons Hotel Los Angeles at Beverly Hills,"{'service': 5.0, 'cleanliness': 5.0, 'overall'...",I spent my birthday this year at the Four Seas...,2,Great time and location
3,Four Seasons Hotel Los Angeles at Beverly Hills,"{'service': 5.0, 'cleanliness': 4.0, 'overall'...",I just love this hotel. I stay here for work a...,2,Great time and location
4,Four Seasons Hotel Los Angeles at Beverly Hills,"{'service': 5.0, 'cleanliness': 5.0, 'overall'...",We had the best hotel experience to date at Th...,2,Great time and location

In [ ]:
from google.colab import files

final_database = df.copy()
final_database.to_csv("final_database.csv", index=False)
files.download("final_database.csv")

In [ ]:
# import matplotlib.pyplot as plt

# x = range(2, 10)
# plt.plot(x, coherence_values, marker='o')
# plt.xlabel("Número de tópicos")
# plt.ylabel("Coherencia C_V")
# plt.title("Coherencia vs Número de Tópicos")
# plt.show()

In [ ]:
# # seleccionar modelo con mayor coherencia
# optimal_index = coherence_values.index(max(coherence_values))
# optimal_model = model_list[optimal_index]

# # imprimir tópicos
# topics = optimal_model.print_topics(num_words=6)
# for topic in topics:
#     print(topic)